---
driver:
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: debian-7.9.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-7.9.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-7.9.0-amd64
    box_check_update: true

- name: debian-8.2.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-8.2.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-8.2.0-amd64
    box_check_update: true

- name: ubuntu-14.04.3-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-14.04.3-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.3-server-amd64
    box_check_update: true

- name: debian-7-0-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  private_networking: false
  ipv6: true
  driver_config:
    digitalocean_access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
    region: ams3
    size: 512mb
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>

suites:
- name: default
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: .data_bags/insecure_databag_secret
  run_list:
    - recipe[dop_varnish::default]
  attributes: {}