language: ruby
sudo: false
bundler_args: "--without kitchen_vagrant --without development"
rvm:
- 2.2.3
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
notifications:
  slack:
    secure: P43+OOgSGOBK0a8okq/nEj6izSEoXqO083OieKWUcvKxRGflCb0zLKuFHJtsSTdOu39q3ALqiy9rucgaBItLNlxkya0SB/0AQybQiAaifndYbn2q0KEKaqWrFurkflNWsWlkq4p+N9fVxj6sn3SSqIfxZrLB9pCVsX2X2F+Z+IU=
